name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      test-suite:
        description: 'Specify the test suite to run'
        required: false
        default: 'all'
      browser:
        type: choice
        description: 'Specify the browser to run tests on (chromium, firefox, webkit)'
        required: true
        options:
          - chromium
          - firefox
          - webkit
        default: 'chromium'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      # BASE_URL: ${{ secrets.BASE_URL }}
      # Use browser input if available, otherwise default to chromium
      BROWSER: ${{ github.event.inputs.browser || 'chromium' }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Debug workflow inputs
      run: |
        echo "Browser: $BROWSER"
        echo "Test suite: ${{ github.event.inputs['test-suite'] }}"
        echo "BASE_URL: $BASE_URL"
    - name: Run Playwright tests
      run: |
        TEST_SUITE="${{ github.event.inputs['test-suite'] }}"
        if [ -z "$BROWSER" ]; then
          echo "Error: browser input is not set!"
          exit 1
        fi
        if [ -n "$TEST_SUITE" ] && [ "$TEST_SUITE" != "all" ]; then
          npx playwright test --project "$BROWSER" --grep "@$TEST_SUITE" --reporter=list,html
        else
          npx playwright test --project "$BROWSER" --reporter=list,html
        fi
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30